# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: golang:1.15-alpine

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: go vet ./...
      - run: golint -set_exit_status $(go list ./...)
      - run: out=$(go fmt ./...) && if [[ -n "$out" ]]; then echo "$out"; exit 1; fi
      - run: go test -short -cover -coverprofile=c.out -v ./...
      - run: go tool cover -html=c.out -o coverage.html
